version: "3.9"
services:
  postgres-chatia:
    image: postgres:16-alpine
    container_name: ms_chatia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatia_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_chatia_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-pagos:
    image: postgres:16-alpine
    container_name: ms_pagos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagos_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_pagos_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ms_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_ms_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_chatia_data:
  postgres_pagos_data:
  redis_ms_data:
